services:
  minio:
    container_name: minio
    image: minio/minio
    networks:
      - my_network
    ports:
      - "9000:9000"
      - "9090:9090"
    volumes:
      - ./mount/minio/data:/data
      - ./mount/minio-config:/root/.minio
    environment:
      - MINIO_ROOT_USER=admin
      - MINIO_ROOT_PASSWORD=password
    command: server /data --console-address ":9090"
    healthcheck:
        test: ["CMD", "curl", "-f", "http://localhost:9090"]
        interval: 3s
        timeout: 3s
        retries: 2
  createbucket:
    image: minio/mc
    networks:
      - my_network
    depends_on:
      minio:
        condition: service_healthy
    entrypoint: >
      /bin/sh -c "
      /usr/bin/mc alias set myminio http://minio:9000 admin password;
      /usr/bin/mc mb myminio/warehouse;
      exit 0;
      "
  postgres:
    container_name: postgres
    image: postgres:14.2-alpine
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: hive
      POSTGRES_PASSWORD: hive123
      POSTGRES_DB: metastore_db
    depends_on: 
      - minio
    networks:
      - my_network
    volumes:
      - ./mount/postgres/data:/var/lib/postgresql/data
  hive-metastore:
    container_name: hive-metastore
    build: ./images/hive-metastore
    ports:
      - 9083:9083
    depends_on:
      - postgres
    networks:
      - my_network
    restart: always
  spark-master:
    container_name: spark-master
    build: ./images/spark
    ports:
      - "5050:5050"
      - "7077:7077"
    depends_on:
      - postgres
    networks:
      - my_network
    environment:
      - MINIO_ROOT_USER=admin
      - MINIO_ROOT_PASSWORD=password
      - SPARK_LOCAL_IP=spark-master
    command: usr/local/spark/bin/spark-class org.apache.spark.deploy.master.Master --ip spark-master --port 7077 --webui-port 5050
  spark-worker-a:
    container_name: spark-worker-a
    build: ./images/spark
    depends_on:
      - spark-master
    networks:
      - my_network
    ports:
      - "5051:5051"
    environment:
      - MINIO_ROOT_USER=admin
      - MINIO_ROOT_PASSWORD=password
      - SPARK_LOCAL_IP=spark-worker-a
    command: usr/local/spark/bin/spark-class org.apache.spark.deploy.worker.Worker --webui-port 5051 spark://spark-master:7077
  trino:
    container_name: trino
    build: ./images/trino
    depends_on:
      - hive-metastore
      - createbucket
    networks:
      - my_network
    ports:
      - "8080:8080"
    environment:
      - MINIO_ROOT_USER=admin
      - MINIO_ROOT_PASSWORD=password
  airflow:
    container_name: airflow
    build: ./images/airflow
    depends_on:
      - trino
      - spark-worker-a
      - createbucket
    networks:
      - my_network
    ports:
      - "8081:8080"
      - "4050:4040"
    environment:
      - _AIRFLOW_WWW_USER_CREATE=true
      - _AIRFLOW_WWW_USER_USERNAME=airflow
      - _AIRFLOW_WWW_USER_PASSWORD=airflow
      - AIRFLOW__CORE__LOAD_EXAMPLES=false
    volumes:
      - ./mount/airflow/dags:/opt/airflow/dags
      - ./mount/airflow/scripts:/opt/airflow/scripts
networks:
  my_network:
    driver: bridge
    name: my_network